### ISSUE TITLE
the versions of Allenact and Ai2thor  

### ISSUE THREAD

**Issue by snow2white** [KuoHaoZeng/Interactive_Visual_Navigation#2]
Hello, excuse me may I ask what are your versions of Allenact and Ai2thor

**Comment by KuoHaoZeng** [comment]
In this repo, the AllenAct is 0.2.0 and the AI2THOR is a slightly modified version of 2.7.4 (to speed up the physics simulation in Unity).
The script will download the correct [version](https://github.com/KuoHaoZeng/Interactive_Visual_Navigation/blob/main/interactive_navigation/constants.py#L7) of AI2THOR for you.

**Comment by KuoHaoZeng** [comment]
issue closed.
please reopen it if you have further questions!
